const search=document.getElementById('search'),category=document.getElementById('category'),results=document.getElementById('results'),count=document.getElementById('count'),clear=document.getElementById('clear'),modal=document.getElementById('gameModal'),area=document.getElementById('gameArea'),title=document.getElementById('gameTitle'),help=document.getElementById('gameHelp');
let query='',cat='';
const categories=[...new Set(GAMES.map(g=>g.category))].sort(); categories.forEach(c=>category.insertAdjacentHTML('beforeend',`<option>${c}</option>`));
function render(){const q=query.toLowerCase();const list=GAMES.filter(g=>(!q||`${g.name} ${g.description} ${g.category}`.toLowerCase().includes(q))&&(!cat||g.category===cat));count.textContent=`${list.length} game${list.length===1?'':'s'}`;results.innerHTML=list.map(g=>`<button class="card" data-id="${g.id}"><h2>${g.id}. ${g.name}</h2><p>${g.description}</p><span class="tag">${g.category}</span></button>`).join('')||'<div class="empty">No games found.</div>';results.querySelectorAll('.card').forEach(b=>b.onclick=()=>openGame(+b.dataset.id));}
search.oninput=()=>{query=search.value;render()};category.onchange=()=>{cat=category.value;render()};clear.onclick=()=>{search.value='';category.value='';query='';cat='';render()};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{cat=b.dataset.filter;category.value=cat;render()});document.getElementById('closeGame').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};
function openGame(id){const g=GAMES.find(x=>x.id===id);title.textContent=`${g.id}. ${g.name}`;help.textContent=g.description;modal.hidden=false;area.innerHTML='';const fn=GAME_TYPES[g.type]||GAME_TYPES.click;fn(area,g);}
const GAME_TYPES={
click(a){let score=0,time=10;a.innerHTML=`<div class="score">Score: <b id="s">0</b> • Time: <b id="t">10</b>s</div><div class="game-controls"><button id="go">CLICK!</button><button id="restart">Restart</button></div>`;let go=a.querySelector('#go'),s=a.querySelector('#s'),t=a.querySelector('#t'),timer;function start(){score=0;let n=10;s.textContent=0;t.textContent=n;clearInterval(timer);timer=setInterval(()=>{t.textContent=--n;if(n<=0){clearInterval(timer);go.disabled=true}},1000);go.disabled=false}go.onclick=()=>{score++;s.textContent=score};a.querySelector('#restart').onclick=start;start()},
ttt(a){a.innerHTML='<div class="game-board" style="grid-template-columns:repeat(3,82px)" id="b"></div><div class="score" id="m">Your turn</div><div class="game-controls"><button id="r">Restart</button></div>';const b=a.querySelector('#b'),m=a.querySelector('#m');let cells=Array(9).fill(''),turn='X';function win(p){return[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(x=>x.every(i=>cells[i]===p))}function draw(){b.innerHTML=cells.map((x,i)=>`<button class="cell" data-i="${i}">${x}</button>`).join('');b.querySelectorAll('button').forEach(x=>x.onclick=()=>move(+x.dataset.i))}function move(i){if(cells[i]||turn!=='X')return;cells[i]='X';if(win('X'))return end('You win!');if(cells.every(Boolean))return end('Draw!');turn='O';draw();setTimeout(ai,250)}function ai(){const free=cells.map((x,i)=>x?null:i).filter(x=>x!==null);if(!free.length)return;cells[free[Math.floor(Math.random()*free.length)]]='O';if(win('O'))return end('Computer wins!');if(cells.every(Boolean))return end('Draw!');turn='X';m.textContent='Your turn';draw()}function end(x){m.textContent=x;turn='-';draw()}a.querySelector('#r').onclick=()=>{cells.fill('');turn='X';m.textContent='Your turn';draw()};draw()},
rps(a){a.innerHTML='<div class="game-controls"><button data-x="Rock">🪨 Rock</button><button data-x="Paper">📄 Paper</button><button data-x="Scissors">✂️ Scissors</button></div><div class="score" id="out">Choose one!</div>';const out=a.querySelector('#out');a.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{const p=b.dataset.x,c=['Rock','Paper','Scissors'][Math.floor(Math.random()*3)];const win=(p==='Rock'&&c==='Scissors')||(p==='Paper'&&c==='Rock')||(p==='Scissors'&&c==='Paper');out.textContent=`You: ${p} • Computer: ${c} — ${p===c?'Draw!':win?'You win!':'Computer wins!'}`})},
guess(a){let n=Math.floor(Math.random()*100)+1; a.innerHTML='<div class="game-controls"><input id="g" type="number" min="1" max="100" placeholder="1-100"><button id="b">Guess</button></div><div class="score" id="o">Guess the number!</div>';a.querySelector('#b').onclick=()=>{let v=+a.querySelector('#g').value,o=a.querySelector('#o');if(v===n){o.textContent='Correct! New number.';n=Math.floor(Math.random()*100)+1}else if(v<n)o.textContent='Too low!';else o.textContent='Too high!'}},
dice(a){a.innerHTML='<div class="score" id="d">Roll the dice!</div><div class="game-controls"><button id="r">Roll</button></div>';a.querySelector('#r').onclick=()=>{let p=Math.floor(Math.random()*6)+1,c=Math.floor(Math.random()*6)+1;a.querySelector('#d').textContent=`You rolled ${p}. Computer rolled ${c}. ${p===c?'Draw!':p>c?'You win!':'Computer wins!'}`}},
math(a){let score=0,n1,n2; a.innerHTML='<div class="score" id="q"></div><div class="game-controls"><input id="v" type="number"><button id="b">Answer</button></div>';const q=a.querySelector('#q'),v=a.querySelector('#v');function next(){n1=Math.floor(Math.random()*20)+1;n2=Math.floor(Math.random()*20)+1;q.textContent=`${n1} + ${n2} = ?`;v.value='';v.focus()}a.querySelector('#b').onclick=()=>{if(+v.value===n1+n2){score++;q.textContent=`Correct! Score ${score}`;setTimeout(next,400)}else q.textContent=`Try again! Score ${score}`};next()},
memory(a){const icons=['🍎','🍌','🍇','⭐','🚀','🎲','🐱','⚽'];let deck=[...icons,...icons].sort(()=>Math.random()-.5),open=[],matched=0;a.innerHTML='<div class="memory-grid" id="mg"></div><div class="score" id="ms">Matches: 0/8</div>';const grid=a.querySelector('#mg');function draw(){grid.innerHTML=deck.map((x,i)=>`<button data-i="${i}">${open.includes(i)||deck[i]==='_'?x:'?'}</button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>flip(+b.dataset.i))}function flip(i){if(open.includes(i)||deck[i]==='_'||open.length===2)return;open.push(i);draw();if(open.length===2){let [x,y]=open;if(deck[x]===deck[y]){deck[x]=deck[y]='_';matched++;open=[];a.querySelector('#ms').textContent=`Matches: ${matched}/8`;draw()}else setTimeout(()=>{open=[];draw()},600)}}draw()},highlow(a){let current=Math.floor(Math.random()*13)+1,score=0;a.innerHTML='<div class="score" id="h"></div><div class="game-controls"><button id="hi">Higher</button><button id="lo">Lower</button></div>';const h=a.querySelector('#h');function show(){h.textContent=`Card: ${current} • Score: ${score}`};a.querySelector('#hi').onclick=()=>play(true);a.querySelector('#lo').onclick=()=>play(false);function play(high){let n=Math.floor(Math.random()*13)+1;if((high&&n>=current)||(!high&&n<=current)){score++;current=n}else{score=0;current=n}show()}show()},reaction(a){a.innerHTML='<div class="score" id="rt">Wait...</div><div class="game-controls"><button id="b">START</button></div>';const t=a.querySelector('#rt'),b=a.querySelector('#b');let ready=false,start=0;b.onclick=()=>{if(ready){t.textContent=`Reaction: ${Date.now()-start} ms`;ready=false;b.textContent='START'}else{t.textContent='Wait...';b.textContent='CLICK!';setTimeout(()=>{ready=true;start=Date.now();t.textContent='NOW!'},1000+Math.random()*2500)}}},
};
// Lightweight fallbacks make every catalog entry playable without external assets.
for(const key of ['connect','grid','color','coin','oddeven','sudoku','merge','mines','lights','simon','typing','target','dodge','lanes','jump','snake','pong','breakout','flappy','catch','chess','checkers','dots','battle','corners','nim','race','stack','helicopter','cave','scramble','wordsearch','hangman','anagram','wordmemory','spelling','trivia','pattern','sequence','maze','keeper','penalty','basket','golf','tennis','hockey','bowling','baseball','soccer','volley','strategy','builder','clicker','miner','manager','mixer','choice','map','orbit','balance'])GAME_TYPES[key]=GAME_TYPES.click;
render();
