const GAMES = [
['Tic-Tac-Toe','Board','Classic 3×3 X and O.','ttt'],['Connect Four','Board','Get four in a row.','connect'],['Memory Match','Puzzle','Match all the hidden pairs.','memory'],['Reaction Test','Arcade','Click when the screen changes.','reaction'],['Number Guess','Puzzle','Guess the secret number.','guess'],['Rock Paper Scissors','Arcade','Beat the computer.','rps'],['Click Rush','Arcade','Click as many times as possible.','click'],['High or Low','Cards','Guess the next number.','highlow'],['Dice Duel','Board','Roll against the computer.','dice'],['Quick Math','Puzzle','Solve as many sums as you can.','math'],
['Grid Runner','Arcade','Reach the goal on a grid.','grid'],['Color Tap','Reaction','Tap the requested color.','color'],['Coin Flip','Arcade','Pick heads or tails.','coin'],['Odd or Even','Puzzle','Predict the next roll.','oddeven'],['Mini Sudoku','Puzzle','Fill a simple number grid.','sudoku'],['2048 Mini','Puzzle','Combine matching numbers.','merge'],['Mines Mini','Puzzle','Find the safe squares.','mines'],['Lights Out','Puzzle','Turn every light off.','lights'],['Simon Says','Memory','Remember the sequence.','simon'],['Typing Race','Action','Type the displayed word.','typing'],
['Target Click','Arcade','Hit the moving target.','target'],['Space Dodger','Action','Avoid falling obstacles.','dodge'],['Lane Racer','Action','Switch lanes and survive.','lanes'],['Jump Blocks','Arcade','Jump over the blocks.','jump'],['Snake','Arcade','Eat food and grow.','snake'],['Pong','Sports','Classic paddle game.','pong'],['Breakout','Arcade','Break every block.','breakout'],['Flappy Dot','Arcade','Fly through the gaps.','flappy'],['Dodgeball','Action','Avoid the incoming balls.','dodge'],['Falling Catch','Arcade','Catch the falling stars.','catch'],
['Chess Mini','Board','A tiny chess challenge.','chess'],['Checkers Mini','Board','Capture the opponent pieces.','checkers'],['Dots and Boxes','Board','Complete the most boxes.','dots'],['Battleship Mini','Board','Find the hidden ships.','battle'],['Four Corners','Board','Choose the winning corner.','corners'],['Nim','Board','Take the last token.','nim'],['Marble Race','Arcade','Pick a marble and race.','race'],['Tower Stack','Arcade','Stack blocks perfectly.','stack'],['Helicopter','Action','Keep flying through gaps.','helicopter'],['Cave Fly','Action','Navigate a narrow cave.','cave'],
['Word Scramble','Puzzle','Unscramble the word.','scramble'],['Word Search','Puzzle','Find the hidden word.','wordsearch'],['Hangman Lite','Puzzle','Guess the letters.','hangman'],['Anagram','Puzzle','Build a word from letters.','anagram'],['Memory Words','Memory','Remember the word order.','wordmemory'],['Spelling Bee','Puzzle','Choose the correct spelling.','spelling'],['Trivia Mix','Puzzle','Answer quick trivia.','trivia'],['Pattern Puzzle','Puzzle','Find what comes next.','pattern'],['Sequence','Puzzle','Complete the number sequence.','sequence'],['Maze','Puzzle','Find your way to the exit.','maze'],
['Goal Keeper','Sports','Save the shots.','keeper'],['Penalty Kick','Sports','Aim for the goal.','penalty'],['Basket Shot','Sports','Score as many baskets as possible.','basket'],['Mini Golf','Sports','Reach the hole in few shots.','golf'],['Tennis Tap','Sports','Return the ball.','tennis'],['Hockey Shot','Sports','Hit the puck into the goal.','hockey'],['Bowling','Sports','Knock down the pins.','bowling'],['Baseball Hit','Sports','Time your swing.','baseball'],['Soccer Dribble','Sports','Keep the ball moving.','soccer'],['Volleyball','Sports','Keep the ball up.','volley'],
['Fireworks','Arcade','Click sparks before they vanish.','click'],['Star Collector','Arcade','Collect stars for points.','catch'],['Gem Match','Puzzle','Match the gems.','merge'],['Bubble Pop','Arcade','Pop the bubbles.','click'],['Balloon Pop','Arcade','Pop balloons quickly.','click'],['Fruit Catch','Arcade','Catch the fruit.','catch'],['Treasure Hunt','Puzzle','Choose the right chest.','guess'],['Monster Tap','Action','Defeat targets with quick taps.','click'],['Robot Dodge','Action','Avoid the robots.','dodge'],['Laser Escape','Action','Move away from the laser.','dodge'],
['Castle Defense','Strategy','Choose the best defense.','strategy'],['Island Builder','Strategy','Grow your island.','builder'],['Farm Clicker','Strategy','Grow your farm.','clicker'],['Space Miner','Strategy','Mine resources.','miner'],['Factory Manager','Strategy','Balance production.','manager'],['Potion Mixer','Strategy','Match the ingredients.','mixer'],['Dungeon Choice','Strategy','Choose a safe path.','choice'],['Treasure Map','Strategy','Find the hidden treasure.','map'],['Kingdom Quiz','Strategy','Make the best choice.','choice'],['Robot Factory','Strategy','Build the correct robot.','builder'],
['Color Memory','Memory','Remember the color sequence.','simon'],['Sound Memory','Memory','Remember the button sequence.','simon'],['Flash Cards','Memory','Remember the cards.','memory'],['Pair Finder','Memory','Find matching pairs.','memory'],['Quick Recall','Memory','Remember the shown number.','guess'],['Pattern Memory','Memory','Copy the pattern.','pattern'],['Emoji Memory','Memory','Match the emoji pairs.','memory'],['Order Memory','Memory','Remember the order.','wordmemory'],['Path Memory','Memory','Repeat the shown path.','grid'],['Sequence Tap','Memory','Tap numbers in order.','sequence'],
['Gravity Ball','Physics','Guide the ball to safety.','dodge'],['Orbit','Physics','Keep the planet in orbit.','orbit'],['Magnet Maze','Physics','Move the magnet to the goal.','grid'],['Balance','Physics','Keep the bar balanced.','balance'],['Bouncy Ball','Physics','Bounce to the target.','jump'],['Rocket Launch','Physics','Choose the launch power.','guess'],['Pendulum','Physics','Time the release.','reaction'],['Wind Rider','Physics','Ride the wind.','dodge'],['Bridge Builder','Physics','Pick a stable bridge.','builder'],['Gravity Switch','Physics','Flip gravity to reach the goal.','grid']
].map((g,i)=>({id:i+1,name:g[0],category:g[1],description:g[2],type:g[3]}));
